# This fuckass file is half-deprecated.
# Defining allowed lints in clippy.toml does not work.
# Defining allowed lints in Cargo.toml does not work.
# I'm just gonna use lib.rs for now.

doc-valid-idents = ["GameMaker", "YoYoGames", ".."]
excessive-nesting-threshold = 7
