[package]
name = "libgm"
version = "0.1.1"
authors = ["BioTomateDE <latuskati+cratesio@gmail.com>"]
edition = "2024"
description = "A tool for modding, unpacking and decompiling GameMaker games"
readme = "../README.md"
repository = "https://github.com/BioTomateDE/LibGM"
license = "GPL-3.0"
keywords = ["gamemaker", "gml", "decompiler", "modding", "undertale"]
categories = ["parser-implementations", "game-development", "encoding"]

# Attribute macros (num_enum, list_chunk, named_list_chunk)
[dependencies.macros]
version = "0.1.0"
path = "../macros"
package = "libgm-macros"


# General Crates.io dependencies
[dependencies]
bzip2 = "0.6.1"    # BZip2+QOI encoded images
log = "0.4.29"     # Logging
num_enum = "0.7.5" # Primitive number enums

# Needed to (potentially) deserialize PNG images
[dependencies.image]
version = "0.25.9"
default-features = false
features = ["png"]

# Needed for Game Creation Timestamp in General Info
[dependencies.chrono]
version = "0.4.42"
default-features = false

# Needed for Game UUID in General Info
[dependencies.uuid]
version = "1.19.0"
default-features = false
