[package]
name = "libgm"
version = "0.4.1"
authors = ["BioTomateDE <latuskati+cratesio@gmail.com>"]
edition = "2024"
description = "A tool for modding, unpacking and decompiling GameMaker games"
readme = "../README.md"
repository = "https://github.com/BioTomateDE/LibGM"
license = "GPL-3.0"
keywords = ["gamemaker", "gml", "decompiler", "modding", "undertale"]
categories = ["parser-implementations", "game-development", "encoding"]

[features]
default = ["catch-panic", "check-integrity", "bzip2-image", "png-image"]
full = [
    "catch-panic",
    "check-integrity",
    "game-creation-timestamp",
    "bzip2-image",
    "png-image",
]

catch-panic = []
check-integrity = []
game-creation-timestamp = ["dep:chrono"]
bzip2-image = ["dep:bzip2"]
png-image = ["image/png"]

# Attribute macros (num_enum, list_chunk, named_list_chunk)
[dependencies.macros]
version = "0.1.1"
path = "../macros"
package = "libgm-macros"

# BZip2+QOI encoded images
[dependencies.bzip2]
version = "0.6.1"
optional = true

# Needed for Game Creation Timestamp in General Info
[dependencies.chrono]
version = "0.4.43"
default-features = false
optional = true

# Needed to (potentially) deserialize PNG images
[dependencies.image]
version = "0.25.9"
default-features = false

# Logging
[dependencies.log]
version = "0.4.29"

# Primitive number enums
[dependencies.num_enum]
version = "0.7.5"
