[package]
name = "libgm"
version = "0.1.0"
authors = ["BioTomateDE <latus.kati@gmail.com>"]
edition = "2024"
description = "A tool for modding, unpacking and decompiling GameMaker games"
readme = "../README.md"
repository = "https://github.com/BioTomateDE/LibGM"
license = "GPL-3"
keywords = ["gamemaker", "gml", "decompiler", "modding", "undertale"]
categories = ["parser-implementations", "game-development", "encoding"]

[dependencies]
# Workspace dependencies
macros = { path = "../macros" }

# Crates.io dependencies
bzip2 = "0.6.1"    # BZip2+QOI encoded images
chrono = "0.4.42"  # Creation Timestamp
colored = "3.0.0"  # D
cpu-time = "1.0.0" # Benchmarking
image = "0.25.9"   # Decoding and encoding images
log = "0.4.28"     # Logging
num_enum = "0.7.5" # Primitive number enums
tynm = "0.2.0"     # Typename without path
uuid = "1.18.1"    # Game UUID
