[package]
name = "libgm-cli"
version = "0.1.0"
edition = "2024"
description = "A simple command line interface for interacting with LibGM"
license = "GPL-3"
repository = "https://github.com/BioTomateDE/LibGM"
readme = "../README.md"
keywords = ["cli", "gamemaker"]
categories = ["command-line-utilities"]

[dependencies]
# Workspace dependencies
libgm = { path = "../libgm" }

# Crates.io dependencies
clap = { version = "4.5.51", features = ["derive"] }
log = "0.4.28"
env_logger = "0.11.8"
colored = "3.0.0"
